### ISSUE TITLE
`parse_identifier` fails on quoted UDF

### ISSUE THREAD

**Issue by dwreeves** [Titan-Systems/titan#125]
Test case (note this is for a pre-existing function, not defined by Titan):

```python
from titan.identifiers import parse_FQN
parse_FQN('UDF_DB.UDFS."REPLACE_DIACRITICS(str VARCHAR):VARCHAR(16777216)"')
```

Result:

```python-traceback
Traceback (most recent call last):
  File "~/.venv/lib/python3.11/site-packages/titan/identifiers.py", line 218, in parse_identifier
    name_parts = list(FullyQualifiedIdentifier.parse_string(scoped_name, parse_all=True))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.venv/lib/python3.11/site-packages/pyparsing/core.py", line 1199, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found '.'  (at char 13), (line:1, col:14)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "~/.venv/lib/python3.11/site-packages/titan/identifiers.py", line 263, in parse_FQN
    identifier = parse_identifier(fqn_str, is_db_scoped=is_db_scoped)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.venv/lib/python3.11/site-packages/titan/identifiers.py", line 220, in parse_identifier
    raise pp.ParseException(f"Failed to parse identifier: {identifier}")
pyparsing.exceptions.ParseException: Failed to parse identifier: UDF_DB.UDFS."REPLACE_DIACRITICS(str VARCHAR):VARCHAR(16777216)"  (at char 0), (line:1, col:1)
```

The issue is the quotes are throwing it off:

```python
>>> print(scoped_name)
UDF_DB.UDFS."REPLACE_DIACRITICS
````

Another issue I've noticed is `arg_types` does not play nicely with the return type in this context:

```python
>>> print(arg_types)
['str VARCHAR):VARCHAR(16777216)"']
```

Original DDL for UDF:

```sql
create or replace function udf_db.udfs.replace_diacritics("str" string)
returns string
language javascript
strict immutable
as
$$
    return str.normalize("NFD").replace(/\p{Diacritic}/gu, "");
$$;
```

**Comment by teej** [comment]
Snowflake has a buggy implementation when it comes to quoted argument names in UDFs. I'll take another look to see if there's a workaround, but I might not be able to fix without escalating to Snowflake.

**Comment by teej** [comment]
Actually on second glance this should be fixable, let me see what I can do.

**Comment by dwreeves** [comment]
I don't know whether the return type thing is intentional but you can potentially fix like this?:

```python
    if "(" in scoped_name:
        args_start = scoped_name.find("(")
        if scoped_name.endswith('"'):
            scoped_name = scoped_name.strip('"')
            scoped_name, args_str = scoped_name[:args_start], scoped_name[args_start:]
            scoped_name += '"'
        else:
            scoped_name, args_str = scoped_name[:args_start], scoped_name[args_start:]
        arg_types = [arg.strip() for arg in args_str.strip("()").split(",")]
```

output:

```python
scoped_name
'BV_ADMIN.UDFS."REPLACE_DIACRITICS"'
arg_types
['str VARCHAR):VARCHAR(16777216']
```

**Comment by dwreeves** [comment]
I don't know whether the return type thing is intentional but you can potentially fix like this?:

```python
    if "(" in scoped_name:
        args_start = scoped_name.find("(")
        if scoped_name.endswith('"'):
            scoped_name = scoped_name.strip('"')
            scoped_name, args_str = scoped_name[:args_start], scoped_name[args_start:]
            scoped_name += '"'
        else:
            scoped_name, args_str = scoped_name[:args_start], scoped_name[args_start:]
        arg_types = [arg.strip() for arg in args_str.strip("()").split(",")]
```

output:

```python
scoped_name
'UDF_DB.UDFS."REPLACE_DIACRITICS"'
arg_types
['str VARCHAR):VARCHAR(16777216']
```

^ But what to do about return type? For overloaded functions, does return type actually matter, or is the FQN fully identifiable by input types only? If latter, then you can split on `:`.
