### ISSUE TITLE
Dependency on Snowflake Connector seems to be causing issue with RSA Keys

### ISSUE THREAD

**Issue by GJMcClintock** [Titan-Systems/titan#166]
I just upgraded to the latest release and started getting an error:

```Traceback (most recent call last):
  File "/Users/garrett/Documents/GitHub/data-platform/.venv/lib/python3.12/site-packages/snowflake/connector/ocsp_snowflake.py", line 1125, in validate_by_direct_connection
    self.process_ocsp_response(issuer, cert_id, ocsp_response)
  File "/Users/garrett/Documents/GitHub/data-platform/.venv/lib/python3.12/site-packages/snowflake/connector/ocsp_asn1crypto.py", line 310, in process_ocsp_response
    self.verify_signature(
  File "/Users/garrett/Documents/GitHub/data-platform/.venv/lib/python3.12/site-packages/snowflake/connector/ocsp_asn1crypto.py", line 372, in verify_signature
    public_key.verify(
TypeError: ECPublicKey.verify() takes 3 positional arguments but 4 were given
```

Even after downgraded to 0.10.13 I still got the error so I figured it was the dependency on the Snowflake connector.

The RSA verification function was changed by Snowflake 2 days ago right after the last release:

new version: https://github.com/snowflakedb/snowflake-connector-python/blob/557774d3e6de714ce4c2f642c7d8aa3ad2577d0d/src/snowflake/connector/ocsp_asn1crypto.py#L357

old version: https://github.com/snowflakedb/snowflake-connector-python/blob/5e61c94691c72e6e7e7a7c83849949a188b72172/src/snowflake/connector/ocsp_asn1crypto.py#L353

This is a breaking change afaict.

**Comment by teej** [comment]
I'll fix this now by pinning

**Comment by teej** [comment]
@GJMcClintock I believe [this to be the root cause](https://github.com/Titan-Systems/titan/pull/168#issuecomment-2504717830), let me know if the most recent version v0.10.21 doesn't work for you.

**Comment by GJMcClintock** [comment]
Yup - that was it. 0.10.21 fixed it. 

Happy Thanksgiving Eve!
