### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by jeff-skoldberg-gmds** [Titan-Systems/titan#31]
## The Error
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2517: character maps to <undefined>

## My environment
Windows 11
Python 11
Clean venv

## steps to reproduce
Powershell
```
python -m venv venv
.\venv\Scripts\activate
pip install git+https://github.com/teej/titan.git
```

## full output
```
Looking in indexes: https://gitlab.beta.team/api/v4/projects/vendors%2Fpypi/packages/pypi/simple
Collecting git+https://github.com/teej/titan.git
  Cloning https://github.com/teej/titan.git to c:\users\jeff\appdata\local\temp\pip-req-build-8fczq4nn
  Running command git clone --filter=blob:none --quiet https://github.com/teej/titan.git 'C:\Users\jeff\AppData\Local\Temp\pip-req-build-8fczq4nn'
  Resolved https://github.com/teej/titan.git to commit aff654a43a66665916497eed1013d74802912e5b
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "C:\Users\jeff\Documents\gmds llc\git\snowflake-stack\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\jeff\Documents\gmds llc\git\snowflake-stack\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\jeff\Documents\gmds llc\git\snowflake-stack\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\jeff\AppData\Local\Temp\pip-build-env-j7tzft0l\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\jeff\AppData\Local\Temp\pip-build-env-j7tzft0l\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\jeff\AppData\Local\Temp\pip-build-env-j7tzft0l\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\jeff\AppData\Local\Temp\pip-build-env-j7tzft0l\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
        File "C:\Python311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2517: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
```

**Comment by titan-teej** [comment]
This looks like a utf-8 issue. I'll try to get a windows build working locally to repro.

**Comment by teej** [comment]
Can you try again? A bad character made it into the README, and the README is read as a part of package installation.

**Comment by andersbergren** [comment]
I just attempted to reinstall on my Windows machine and got the same error.

Windows 11
Python 12
Clean venv

**Comment by jeff-skoldberg-gmds** [comment]
> I just attempted to install on my Windows machine and got the same error.
> 
> Windows 11 Python 12 Clean venv

I am also still getting the same error.

**Comment by jeff-skoldberg-gmds** [comment]
Confirmed, it worked!  Also, I did not have any dependency conflicts this time, so thanks for addressing that too!
