### ISSUE TITLE
ValueError when trying to set a Grant on a Storage Integration

### ISSUE THREAD

**Issue by jcrobak** [Titan-Systems/titan#32]
Sample traceback:
```
Traceback (most recent call last):
  File "failing.py", line 71, in <module>
    plan = bp.plan(session)
           ^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/titan/blueprint.py", line 662, in plan
    remote_state = _fetch_remote_state(session, manifest)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/titan/blueprint.py", line 391, in _fetch_remote_state
    resource_cls = Resource.resolve_resource_cls(urn.resource_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/titan/resources/resource.py", line 226, in resolve_resource_cls
    raise ValueError(f"Cannot resolve polymorphic resource class [{resource_type}] without data")
ValueError: Cannot resolve polymorphic resource class [STORAGE INTEGRATION] without data
```

And here's a small repro case:

```python
import os

from titan import Blueprint
from titan.blueprint import print_plan
from titan.resources import (
    GCSStorageIntegration,
    Grant,
    Role,
)

import snowflake.connector

connection_params = {
    "account": os.environ["SNOWFLAKE_ACCOUNT"],
    "user": os.environ["SNOWFLAKE_USER"],
    "password": os.environ["SNOWFLAKE_PASSWORD"],
}


def resources():
    loader = Role(name="LOADER")

    storage_integration = GCSStorageIntegration(
        name="gcs_int",
        enabled=True,
        storage_allowed_locations=[
            "gcs://bucket/path/",
        ],
    )

    storage_grant = Grant(priv="USAGE", on_storage_integration="gcs_int", to=loader)

    return (
        loader,
        storage_integration,
        storage_grant,
    )


if __name__ == "__main__":
    bp = Blueprint(name="repro-failing-reference")
    bp.add(*resources())
    session = snowflake.connector.connect(**connection_params)
    plan = bp.plan(session)
    print_plan(plan)
```

at a quick reading of the code, it's not immediately obviously to me how to solve this. We can pass along data to `resolve_resource_cls`, but in this case there isn't any data because the storage integration doesn't exist yet.

**Comment by teej** [comment]
Found the issue, the next release will include the fix.
