### ISSUE TITLE
InternalStage missing implementation

### ISSUE THREAD

**Issue by dexhorthy** [Titan-Systems/titan#34]
Guessing this is just a "todo" kind of thing, but didn't see an issue for it already - unable to create a stage using the `InternalStage` resource.

overall, enjoying working with titan so far though 🚀 

### repro

this one works

```python 
    bp = Blueprint(name="odp-napp-setup")

    odp_app_packager_role = Role(name='ODP_APP_PACKAGER_ROLE')

    staging_db = Database(name='ODP_APP_STAGING', owner=odp_app_packager_role.name)
    staging_schema = Schema(name='NAPP', database=staging_db, owner=odp_app_packager_role.name)

    bp.add(
        odp_app_packager_role,
        staging_db,
        staging_schema,
    )
    session = snowflake.connector.connect(**connection_params)
    plan = bp.plan(session)
    print(plan)

    bp.apply(session, plan)
```

but as soon as I try to add a stage, it blows up with `NotImplementedError`

```python
    bp = Blueprint(name="odp-napp-setup")

    odp_app_packager_role = Role(name='ODP_APP_PACKAGER_ROLE')

    staging_db = Database(name='ODP_APP_STAGING', owner=odp_app_packager_role.name)
    staging_schema = Schema(name='NAPP', database=staging_db, owner=odp_app_packager_role.name)
    staging_stage = InternalStage(
        name='APP_STAGE',
        database=staging_db,
        schema=staging_schema,
        owner=odp_app_packager_role.name,
    )

    bp.add(
        odp_app_packager_role,
        staging_db,
        staging_schema,
        staging_stage,
    )
    session = snowflake.connector.connect(**connection_params)
    plan = bp.plan(session)
    print(plan)

    bp.apply(session, plan)
```

stack trace is here:

```
rbac-1  | Traceback (most recent call last):
rbac-1  |   File "/opt/project/snowpark/rbac/main.py", line 84, in <module>
rbac-1  |     plan = bp.plan(session)
rbac-1  |            ^^^^^^^^^^^^^^^^
rbac-1  |   File "/usr/local/lib/python3.11/site-packages/titan/blueprint.py", line 662, in plan
rbac-1  |     remote_state = _fetch_remote_state(session, manifest)
rbac-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rbac-1  |   File "/usr/local/lib/python3.11/site-packages/titan/blueprint.py", line 359, in _fetch_remote_state
rbac-1  |     data = data_provider.fetch_resource(session, urn)
rbac-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rbac-1  |   File "/usr/local/lib/python3.11/site-packages/titan/data_provider.py", line 167, in fetch_resource
rbac-1  |     return getattr(__this__, f"fetch_{urn.resource_label}")(session, urn.fqn)
rbac-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rbac-1  |   File "/usr/local/lib/python3.11/site-packages/titan/data_provider.py", line 782, in fetch_stage
rbac-1  |     raise NotImplementedError
rbac-1  | NotImplementedError
```

**Comment by dexhorthy** [comment]
ah, looks like #35 marks `InternalStage` as WIP again 👍 will stand by then

**Comment by teej** [comment]
@dexhorthy Let me take a look

**Comment by teej** [comment]
Added in https://github.com/Titan-Systems/titan/releases/tag/v0.4.1

**Comment by dexhorthy** [comment]
thank you!
